lime.loadMap("<#mapNametmx#>",<#baseDirectory#>)
lime.createVisual(<#mapName#>)
lime.buildPhysical(<#mapName#>)
lime.createTileLayer(<#mapName#>, "<#layerName#>")
lime.createObjectLayer(<#mapName#>, "<#layerName#>")
lime.verifyVersion( )
lime.enableDebugMode()
lime.disableDebugMode()
lime.isDebugModeEnabled()
lime.enableScreenCulling()
lime.disableScreenCulling()
lime.isScreenCullingEnabled()
lime.createAtlas()
lime.registerInterface(<#mapName#>)
lime.loadCustomMap("<#mapNametmx#>",<#baseDirectory#>, <#params#>)
lime.createAtlas()
utils.isometricToWorldPosition(<#mapName#>, <#position#>)
utils.worldToIsometricPosition(<#mapName#>, <#position#>)
utils.worldToGridPosition(<#mapName#>, <#position#>)
utils.gridToWorldPosition(<#mapName#>, <#position#>, <#offset#> )
utils.screenToGridPosition(<#mapName#>, <#position#>)
utils.screenToWorldPosition(<#mapName#>, <#position#>)
utils.worldToScreenPosition(<#mapName#>, <#position#>)
map:
map:getProperty("<#propertyName#>")
map:getPropertyValue("<#propertyName#>")
map:getProperties()
map:getPropertyCount()
map:hasProperty("<#name#>")
map:addProperty(<#property#>)
map:removeProperty("<#propertyName#>")
map:move(<#xAmount#>, <#yAmount#>)
map:drag(<#event#>)
map:show()
map:hide()
map:getVisual()
map:setRotation(<#degrees#>)
map:rotate(<#angle#>)
map:setScale(<#xScale#>, <#yScale#>)
map:scale(<#xScale#>, <#yScale#>)
map:getScale()
map:setPosition(<#xPos#>, <#yPos#>)
map:getPosition()
map:fadeToPosition(<#xPos#>, <#yPos#>, <#fadeTime#>, <#movedelay#>, <#onCompleteHandler#>)
map:slideToPosition(<#xPos#>, <#yPos#>, <#slideTime#>, <#onCompleteHandler#>)
map:showDebugImages()
map:hideDebugImages()
map:toggleDebugImagesVisibility()
map:getTilesAt(<#position#>, <#count#>, <#BOOL#>)
map:getTileAt(<#position#>, <#BOOL#>)
map:getTilesWithProperty("<#propertyName#>")
map:getObjectsWithProperty("<#propertyName#>")
map:getObjectsWithName("<#name#>")
map:getObjectsWithType("<#objectType#>")
map:findValuesByTilePropertyName("<#propertyName#>")
map:createSprite(<#GIDnumber#>)
map:createTile(<#GIDnumber#>, "<#layerName#>")
map:createAndBuildTile(<#GIDnumber#>, "<#layerName#>")
map:createTileAt(<#GIDnumber#>, "<#layerName#>", { row = <#number#>, column = <#number#>})
map:createAndBuildTileAt(<#GIDnumber#>, "<#layerName#>", { row = <#number#>, column = <#number#>})
map:getTilePropertyValueForGID(<#GIDnumber#>, "<#propertyName#>" )
map:getGIDForTileNameID("<#tileSetName#>", <#GIDnumber#>)
map:getTileNameIDForGID(<#GIDnumber#>)
map:addObject(<#object#>)
map:addObjectListener("<#objectType#>", <#listener#>)
map:getObjectListeners()
map:addPropertyListener("<#propertyName#>", <#listener#>)
map:getPropertyListeners()
map:setFocus(<#object#>)
map:update(<#event#>)
map:enableScreenClamping()
map:disableScreenClamping()
map:isScreenClampingEnabled()
map:create()
map:build()
map:destroy()
tileLayer:
tileLayer:getProperty("<#propertyName#>")
tileLayer:getPropertyValue("<#propertyName#>")
tileLayer:getProperties()
tileLayer:getPropertyCount()
tileLayer:hasProperty("<#propertyName#>")
tileLayer:addProperty(<#property#>)
tileLayer:removeProperty("<#propertyName#>")
tileLayer:move(<#xAmount#>, <#yAmount#>)
tileLayer:drag(<#event#>)
tileLayer:show()
tileLayer:hide()
tileLayer:getVisual()
tileLayer:setRotation(<#degrees#>)
tileLayer:rotate(<#angle#>)
tileLayer:getTileAt(<#position#>, <#BOOL#>)
tileLayer:getTilesWithProperty("<#propertyName#>")
tileLayer:swapTiles(<#tile1#>, <#tile2#>)
tileLayer:swapTilesAtPositions(<#position1#>, <#position2#>)
tileLayer:removeTileAt(<#position#>)
tileLayer:setTileAt(<#GIDnumber#>, <#position#>)
tileLayer:createTile(<#GIDnumber#>)
tileLayer:createAndBuildTile(<#GIDnumber#>)
tileLayer:addObject(<#object#>)
tileLayer:setPosition(<#xPosition#>, <#yPosition#>, <#BOOL#>)
tileLayer:create()
tileLayer:build()
tileLayer:destroy()
objectLayer:
objectLayer:getProperty("<#propertyName#>")
objectLayer:getPropertyValue("<#propertyName#>")
objectLayer:getProperties("<#propertyName#>")
objectLayer:getPropertyCount()
objectLayer:hasProperty()
objectLayer:addProperty(<#propertyObject#>)
objectLayer:removeProperty("<#propertyName#>")
objectLayer:move(<#xAmount#>, <#yAmount#>)
objectLayer:drag(<#event#>)
objectLayer:show()
objectLayer:hide()
objectLayer:getVisual()
objectLayer:setRotation(<#degrees#>)
objectLayer:rotate(<#angle#>)
objectLayer:getObject("<#objectName#>", "<#objectType#>")
objectLayer:getObjects("<#objectName#>", "<#objectType#>")
objectLayer:getObjectsWithProperty("<#propertyName#>")
objectLayer:getObjectsWithName("<#objectName#>")
objectLayer:getObjectsOfType("<#objectType#>")
objectLayer:setPosition(<#xPosition#>, <#yPosition#>)
objectLayer:addObject(<#displayObject#>)
objectLayer:showDebugImages()
objectLayer:hideDebugImages()
objectLayer:toggleDebugImagesVisibility()
objectLayer:create()
objectLayer:build()
objectLayer:destroy()
tile:
tile:getProperty("<#propertyName#>")
tile:getPropertyValue("<#propertyName#>")
tile:getProperties()
tile:getPropertyCount()
tile:hasProperty("<#propertyName#>")
tile:addProperty(<#propertyObject#>)
tile:removeProperty()
tile:move(<#xAmount#>, <#yAmount#>)
tile:drag(<#event#>)
tile:show()
tile:hide()
tile:getVisual()
tile:setRotation(<#degrees#>)
tile:rotate(<#angle#>)
tile:setImage(<#GIDnumber#>)
tile:updateGridPosition()
tile:slideToPosition(<#xPos#>, <#yPos#>, <#slideTime#>, <#onCompleteHandler#>)
tile:fadeToPosition(<#xPos#>, <#yPos#>, <#fadeTime#>, <#moveDelay#>, <#onCompleteHandler#>)
tile:slideAlongPath(<#path#>, <#slideTime#>, <#cycles#>)
tile:getWorldPosition()
tile:getGridPosition()
tile:isOnScreen()
tile:create(<#tileNumber#>)
tile:build()
tile:destroy()
object:
object:setProperty("<#propertyName#>", "<#propertyValue#>")
object:getProperty("<#propertyName#>")
object:getPropertyValue("<#propertyValue#>")
object:getProperties()
object:getPropertyCount()
object:hasProperty("<#propertyName#>")
object:addProperty(<#propertyObjectName#>)
object:removeProperty("<#propertyName#>")
object:setPosition(<#xPos#>, <#yPos#>)
object:getPosition()
object:getObjectTilePropertyValue("<#propertyValue#>")
object:move(<#xAmount#>, <#yAmount#>)
object:drag(<#event#>)
object:show()
object:hide()
object:getVisual()
object:setRotation(<#degrees#>)
object:rotate(<#angle#>)
object:showDebugImage()
object:hideDebugImage()
object:isDebugImageVisible()
object:toggleDebugImageVisibility()
object:create()
object:build()
object:destroy()
property:
property:getName()
property:getValue()
property:setValue("<#propertyValue#>")
tileSet:
tileSet:setProperty("<#propertyName#>", "<#propertyValue#>")
tileSet:getProperty("<#propertyName#>")
tileSet:getPropertyValue("<#propertyValue#>")
tileSet:getProperties()
tileSet:getPropertyCount()
tileSet:hasProperty("<#propertyName#>")
tileSet:addProperty(<#propertyObjectName#>)
tileSet:removeProperty("<#propertyName#>")
tileSet:createSprite(<#GIDnumber#>)
tileSet:getPropertiesForTile(<#GIDnumber#>)
tileSet:destroy()
