LevelHelperLoader:
Loader:
LevelHelperLoader:initWithContentOfFile("<#levelFileName#>")
LevelHelperLoader:initWithContentOfFileFromResourceDir("<#levelFileName#>", "<#SystemDocumentsDirectory#>")
Loader:instantiateSprites()
Loader:instantiateSpritesInGroup(<#groupName#>)
Loader:instantiateObjects(physics)
Loader:instantiateObjectsInGroup(physics, <#groupName#>)
Loader:instantiateSpritesInGroup(<#groupName#>)
Loader:spriteWithUniqueName("<#mySpriteName#>")
Loader:isSpriteWithUniqueNameInLevel("<#mySpriteName#>")
Loader:jointWithUniqueName("<#jointName#>")
loader:isJointWithUniqueNameInLevel("<#myJoint#>")
Loader:spritesWithTag(<#LevelHelperMySpriteTag#>)
Loader:newObjectWithUniqueName("<#mySpriteName#>", physics)
Loader:removeSpriteWithUniqueName("<#mySpriteName#>")
Loader:removeAllSprites()
Loader:removeJointWithUniqueName("<#mySpriteName#>")
Loader:removeAllJoints()
Loader:removeSpritesWithTag(<#LevelHelperMySpriteTag#>)