coronaui.newScreen(<#width#>, <#statusBarVisible#>, "<#titleString#>", "<#bgImg#>", <#navBarBg#>, <#navBarBgWidth#>, <#navBarBgHeight#> )
slideToLeft(<#gotToScreen#>, <#onCompleteFunction#>)
slideToRight(<#gotToScreen#>, <#onCompleteFunction#>)
addBackButton(<#gotToScreen#>)
addLeftButton("<#buttonText#>", <#eventListener#>, <#isLong#>, <#customImg#>, <#customOverImg#>, <#customWidth#>, <#customHeight#>, <#customLeft#>, <#customMid#>, <#customRight#>, <#customOverLeft#>, <#customOverMid#>, <#customOverRight#>)
addRightButton("<#buttonText#>", <#eventListener#>, <#isLong#>, <#customImg#>, <#customOverImg#>, <#customWidth#>, <#customHeight#>, <#customLeft#>, <#customMid#>, <#customRight#>, <#customOverLeft#>, <#customOverMid#>, <#customOverRight#>)
insertUnderTitle(<#displayObject#>)
newList(<#top#>, <#bottom#>, <#hasTitleBOOL#>, <#hasStatusBarBOOL#>, <#rowHeight#>, <#selectionListBOOL#>, "<#fillColor#>", <#hideLinesBOOL#>, <#tearEffectBOOL#>, <#scrollDisabledBOOL#>, <#customTitleHeight#>)
addItem({icon = "<#iconNamePNG#>", width = "<#number#>", height = "<#number#>" }, "<#mainTitle#>", "<#subTitle#>", <#onTouch#>, <#hideArrowBOOL#>, <#isCategoryBOOL#>, "<#categoryBgImg#>", <#categoryHeight#>, <#categoryTextR#>, <#categoryTextG#>, <#categoryTextB#>)
removeItem(<#row#>)
removeAllItems()
printItems()
clearSelection()
populateFromXML("<#xmlFileName#>")
copyFromList(<#targetList#>, <#targetScreen#>, <#includeTouchEventsBOOL#>, <#selectionListBOOL#>)
newPicker("<#wheelType#>", <#eventListener#>, <#startYear#>, <#endYear#>, <#selectedFirst#>, <#selectedSecond#>, <#selectedThird#>)
addItem("<#pickerItemName#>")
addItemsFromData(<#dataTable#>)
hidePicker(<#pickerName#>)
createTableList(<#rowsTable#>)
removeMe()
getTextString()
coronaui.newOnOffSwitch(<#x#>, <#y#>, "<#on/off#>")
coronaui.newSliderControl(<#x#>, <#y#>, <#number#>)
coronaui.createTabs(<#buttonsTable#>, <#x#>, <#y#>, <#customLeft#>, <#customMid#>, <#customRight#>, <#customOverLeft#>, <#customOverMid#>, <#customOverRight#>, <#tabLeft#>, <#tabMid#>, <#tabRight#>, <#tabOverLeft#>, <#tabOverRight#>)
coronaui.newSearchScreen(<#listObjectToSearch#>, <#backScreen#>, <#startVisibleBOOL#>, <#width#>, "<#customBackImg#>", <#backImgWidth#>, <#backImgHeight#>, "<#custombackImgOver#>")
coronaui.newRetinaText("<#textString#>", <#x#>, <#y#>, "<#fontName#>", <#fontSize#>, <#R#>, <#G#>, <#B#>, "<#alignment#>", <#emBossOnBOOL#>, <#parentGroup#>)
updateText(<#stringName#>)
